### Should fail with 401
POST http://localhost:8080/api/users/login
username: root
password: toor

### Should succeed with 200
POST http://localhost:8080/api/users/login
username: root
password: root

### Should fail with 406
POST http://localhost:8080/api/users/register
username: root
password: root

### Should succeed with 201 on first time, fail with 406 the second time
POST http://localhost:8080/api/users/register
username: pipsa
password: possu

### Should return root user
GET http://localhost:8080/api/users/1

### Should return toor user
GET http://localhost:8080/api/users/2

### Should return list of all the users
GET http://localhost:8080/api/users

###
POST http://localhost:8080/api/users/1/addfriend/2

###
POST http://localhost:8080/api/users/2/acceptfriend/1

###
POST http://localhost:8080/api/users/1/addpoints
catId: 1
answers: 5
correctAnswers: 3
